version: "3"

services:

  test-setup:
    image: swiftly:18.04-test
    build:
      args:
        base_image: "swift:5.10-bionic"

  test:
    image: swiftly:18.04-test
    environment:
      - SWIFTLY_PLATFORM_NAME=ubuntu1804
      - SWIFTLY_PLATFORM_NAME_FULL=ubuntu18.04
      - SWIFTLY_PLATFORM_NAME_PRETTY="Ubuntu 18.04"

  install-test-setup:
    image: swiftly:18.04-install-test
    build:
      args:
        base_image: "ubuntu:bionic"

  install-test:
    image: swiftly:18.04-install-test

  shell:
    image: swiftly:18.04-test
